from config.database import get_db
from agents.tool.interface.index import State
import json
import os

events = [
    {
        "DayOfWeek": "Monday",
        "title": "Tập thể dục buổi sáng",
        "description": "Khởi động ngày mới với bài tập nhẹ nhàng.",
        "location": "Nhà",
        "start_time": "2024-07-01T06:00:00",
        "end_time": "2024-07-01T06:30:00",
        "icon": "🧘‍♀️",
        "priority": "medium",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Monday",
        "title": "Ăn sáng",
        "description": "Bữa sáng chay lành mạnh.",
        "location": "Nhà",
        "start_time": "2024-07-01T06:30:00",
        "end_time": "2024-07-01T07:00:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Monday",
        "title": "Học tập",
        "description": "Học các môn quan trọng.",
        "location": "Thư viện",
        "start_time": "2024-07-01T07:00:00",
        "end_time": "2024-07-01T11:00:00",
        "icon": "📚",
        "priority": "high",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Monday",
        "title": "Nghỉ ngơi",
        "description": "Nghỉ ngơi giữa buổi học.",
        "location": "Quán cafe",
        "start_time": "2024-07-01T11:00:00",
        "end_time": "2024-07-01T11:30:00",
        "icon": "☕",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Monday",
        "title": "Ăn trưa",
        "description": "Bữa trưa chay.",
        "location": "Nhà",
        "start_time": "2024-07-01T11:30:00",
        "end_time": "2024-07-01T12:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Monday",
        "title": "Làm việc",
        "description": "Giải quyết công việc.",
        "location": "Văn phòng",
        "start_time": "2024-07-01T12:30:00",
        "end_time": "2024-07-01T17:00:00",
        "icon": "💼",
        "priority": "medium",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Monday",
        "title": "Nghỉ ngơi",
        "description": "Đi dạo thư giãn.",
        "location": "Công viên",
        "start_time": "2024-07-01T17:00:00",
        "end_time": "2024-07-01T17:30:00",
        "icon": "🚶‍♀️",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Monday",
        "title": "Ăn tối",
        "description": "Bữa tối chay nhẹ nhàng.",
        "location": "Nhà",
        "start_time": "2024-07-01T18:30:00",
        "end_time": "2024-07-01T19:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Monday",
        "title": "Đọc sách",
        "description": "Đọc sách trước khi ngủ.",
        "location": "Phòng ngủ",
        "start_time": "2024-07-01T21:30:00",
        "end_time": "2024-07-01T22:30:00",
        "icon": "📖",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Tuesday",
        "title": "Ngày vui chơi",
        "description": "Tận hưởng trọn vẹn một ngày vui vẻ.",
        "location": "Không xác định",
        "start_time": "2024-07-02T06:00:00",
        "end_time": "2024-07-02T23:00:00",
        "icon": "🎉",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Tập thể dục buổi sáng",
        "description": "Khởi động ngày mới với bài tập nhẹ nhàng.",
        "location": "Nhà",
        "start_time": "2024-07-03T06:00:00",
        "end_time": "2024-07-03T06:30:00",
        "icon": "🧘‍♀️",
        "priority": "medium",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Ăn sáng",
        "description": "Bữa sáng chay lành mạnh.",
        "location": "Nhà",
        "start_time": "2024-07-03T06:30:00",
        "end_time": "2024-07-03T07:00:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Học tập",
        "description": "Học các môn quan trọng.",
        "location": "Thư viện",
        "start_time": "2024-07-03T07:00:00",
        "end_time": "2024-07-03T11:00:00",
        "icon": "📚",
        "priority": "high",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Nghỉ ngơi",
        "description": "Nghỉ ngơi giữa buổi học.",
        "location": "Quán cafe",
        "start_time": "2024-07-03T11:00:00",
        "end_time": "2024-07-03T11:30:00",
        "icon": "☕",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Ăn trưa",
        "description": "Bữa trưa chay.",
        "location": "Nhà",
        "start_time": "2024-07-03T11:30:00",
        "end_time": "2024-07-03T12:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Làm việc",
        "description": "Giải quyết công việc.",
        "location": "Văn phòng",
        "start_time": "2024-07-03T12:30:00",
        "end_time": "2024-07-03T17:00:00",
        "icon": "💼",
        "priority": "medium",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Nghỉ ngơi",
        "description": "Đi dạo thư giãn.",
        "location": "Công viên",
        "start_time": "2024-07-03T17:00:00",
        "end_time": "2024-07-03T17:30:00",
        "icon": "🚶‍♀️",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Ăn tối",
        "description": "Bữa tối chay nhẹ nhàng.",
        "location": "Nhà",
        "start_time": "2024-07-03T18:30:00",
        "end_time": "2024-07-03T19:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Wednesday",
        "title": "Đọc sách",
        "description": "Đọc sách trước khi ngủ.",
        "location": "Phòng ngủ",
        "start_time": "2024-07-03T21:30:00",
        "end_time": "2024-07-03T22:30:00",
        "icon": "📖",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Tập thể dục buổi sáng",
        "description": "Khởi động ngày mới với bài tập nhẹ nhàng.",
        "location": "Nhà",
        "start_time": "2024-07-04T06:00:00",
        "end_time": "2024-07-04T06:30:00",
        "icon": "🧘‍♀️",
        "priority": "medium",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Ăn sáng",
        "description": "Bữa sáng chay lành mạnh.",
        "location": "Nhà",
        "start_time": "2024-07-04T06:30:00",
        "end_time": "2024-07-04T07:00:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Học tập",
        "description": "Học các môn quan trọng.",
        "location": "Thư viện",
        "start_time": "2024-07-04T07:00:00",
        "end_time": "2024-07-04T11:00:00",
        "icon": "📚",
        "priority": "high",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Nghỉ ngơi",
        "description": "Nghỉ ngơi giữa buổi học.",
        "location": "Quán cafe",
        "start_time": "2024-07-04T11:00:00",
        "end_time": "2024-07-04T11:30:00",
        "icon": "☕",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Ăn trưa",
        "description": "Bữa trưa chay.",
        "location": "Nhà",
        "start_time": "2024-07-04T11:30:00",
        "end_time": "2024-07-04T12:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Làm việc",
        "description": "Giải quyết công việc.",
        "location": "Văn phòng",
        "start_time": "2024-07-04T12:30:00",
        "end_time": "2024-07-04T17:00:00",
        "icon": "💼",
        "priority": "medium",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Nghỉ ngơi",
        "description": "Đi dạo thư giãn.",
        "location": "Công viên",
        "start_time": "2024-07-04T17:00:00",
        "end_time": "2024-07-04T17:30:00",
        "icon": "🚶‍♀️",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Ăn tối",
        "description": "Bữa tối chay nhẹ nhàng.",
        "location": "Nhà",
        "start_time": "2024-07-04T18:30:00",
        "end_time": "2024-07-04T19:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Thursday",
        "title": "Đọc sách",
        "description": "Đọc sách trước khi ngủ.",
        "location": "Phòng ngủ",
        "start_time": "2024-07-04T21:30:00",
        "end_time": "2024-07-04T22:30:00",
        "icon": "📖",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Tập thể dục buổi sáng",
        "description": "Khởi động ngày mới với bài tập nhẹ nhàng.",
        "location": "Nhà",
        "start_time": "2024-07-05T06:00:00",
        "end_time": "2024-07-05T06:30:00",
        "icon": "🧘‍♀️",
        "priority": "medium",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Ăn sáng",
        "description": "Bữa sáng chay lành mạnh.",
        "location": "Nhà",
        "start_time": "2024-07-05T06:30:00",
        "end_time": "2024-07-05T07:00:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Học tập",
        "description": "Học các môn quan trọng.",
        "location": "Thư viện",
        "start_time": "2024-07-05T07:00:00",
        "end_time": "2024-07-05T11:00:00",
        "icon": "📚",
        "priority": "high",
        "event_category": "habit",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Nghỉ ngơi",
        "description": "Nghỉ ngơi giữa buổi học.",
        "location": "Quán cafe",
        "start_time": "2024-07-05T11:00:00",
        "end_time": "2024-07-05T11:30:00",
        "icon": "☕",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Ăn trưa",
        "description": "Bữa trưa chay.",
        "location": "Nhà",
        "start_time": "2024-07-05T11:30:00",
        "end_time": "2024-07-05T12:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Làm việc",
        "description": "Giải quyết công việc.",
        "location": "Văn phòng",
        "start_time": "2024-07-05T12:30:00",
        "end_time": "2024-07-05T17:00:00",
        "icon": "💼",
        "priority": "medium",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Nghỉ ngơi",
        "description": "Đi dạo thư giãn.",
        "location": "Công viên",
        "start_time": "2024-07-05T17:00:00",
        "end_time": "2024-07-05T17:30:00",
        "icon": "🚶‍♀️",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Ăn tối",
        "description": "Bữa tối chay nhẹ nhàng.",
        "location": "Nhà",
        "start_time": "2024-07-05T18:30:00",
        "end_time": "2024-07-05T19:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Friday",
        "title": "Đọc sách",
        "description": "Đọc sách trước khi ngủ.",
        "location": "Phòng ngủ",
        "start_time": "2024-07-05T21:30:00",
        "end_time": "2024-07-05T22:30:00",
        "icon": "📖",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Saturday",
        "title": "Tập thể dục nhẹ nhàng",
        "description": "Yoga hoặc đi bộ.",
        "location": "Công viên",
        "start_time": "2024-07-06T07:00:00",
        "end_time": "2024-07-06T07:30:00",
        "icon": "🚶‍♀️",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Saturday",
        "title": "Ăn sáng",
        "description": "Bữa sáng chay.",
        "location": "Nhà",
        "start_time": "2024-07-06T07:30:00",
        "end_time": "2024-07-06T08:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Saturday",
        "title": "Thư giãn",
        "description": "Xem phim hoặc nghe nhạc.",
        "location": "Nhà",
        "start_time": "2024-07-06T08:30:00",
        "end_time": "2024-07-06T11:30:00",
        "icon": " relaxation",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Saturday",
        "title": "Ăn trưa",
        "description": "Bữa trưa chay.",
        "location": "Nhà",
        "start_time": "2024-07-06T11:30:00",
        "end_time": "2024-07-06T12:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Saturday",
        "title": "Đi chơi",
        "description": "Gặp gỡ bạn bè.",
        "location": "Quán cafe",
        "start_time": "2024-07-06T14:00:00",
        "end_time": "2024-07-06T17:00:00",
        "icon": "☕",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Saturday",
        "title": "Ăn tối",
        "description": "Bữa tối chay.",
        "location": "Nhà",
        "start_time": "2024-07-06T18:30:00",
        "end_time": "2024-07-06T19:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Saturday",
        "title": "Đọc sách",
        "description": "Đọc sách trước khi ngủ.",
        "location": "Phòng ngủ",
        "start_time": "2024-07-06T21:30:00",
        "end_time": "2024-07-06T22:30:00",
        "icon": "📖",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Sunday",
        "title": "Tập thể dục nhẹ nhàng",
        "description": "Yoga hoặc đi bộ.",
        "location": "Công viên",
        "start_time": "2024-07-07T07:00:00",
        "end_time": "2024-07-07T07:30:00",
        "icon": "🚶‍♀️",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Sunday",
        "title": "Ăn sáng",
        "description": "Bữa sáng chay.",
        "location": "Nhà",
        "start_time": "2024-07-07T07:30:00",
        "end_time": "2024-07-07T08:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Sunday",
        "title": "Thư giãn",
        "description": "Xem phim hoặc nghe nhạc.",
        "location": "Nhà",
        "start_time": "2024-07-07T08:30:00",
        "end_time": "2024-07-07T11:30:00",
        "icon": " relaxation",
        "priority": "low",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Sunday",
        "title": "Ăn trưa",
        "description": "Bữa trưa chay.",
        "location": "Nhà",
        "start_time": "2024-07-07T11:30:00",
        "end_time": "2024-07-07T12:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Sunday",
        "title": "Tổng kết tuần",
        "description": "Xem lại những gì đã làm trong tuần.",
        "location": "Nhà",
        "start_time": "2024-07-07T14:00:00",
        "end_time": "2024-07-07T16:00:00",
        "icon": " reflection",
        "priority": "medium",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Sunday",
        "title": "Ăn tối",
        "description": "Bữa tối chay.",
        "location": "Nhà",
        "start_time": "2024-07-07T18:30:00",
        "end_time": "2024-07-07T19:30:00",
        "icon": "🍽️",
        "priority": "high",
        "event_category": "general",
    },
    {
        "DayOfWeek": "Sunday",
        "title": "Đọc sách",
        "description": "Đọc sách trước khi ngủ.",
        "location": "Phòng ngủ",
        "start_time": "2024-07-07T21:30:00",
        "end_time": "2024-07-07T22:30:00",
        "icon": "📖",
        "priority": "low",
        "event_category": "general",
    },
]


def accept_schedule(state: State):
    print("⏳ Saving new schedule from file...")

    # conn = get_db()
    # cursor = conn.cursor()

    # # Tạo bảng nếu chưa có
    # cursor.execute(
    #     """
    #     CREATE TABLE IF NOT EXISTS events (
    #         id SERIAL PRIMARY KEY,
    #         day_of_week TEXT NOT NULL,
    #         title TEXT NOT NULL,
    #         description TEXT,
    #         location TEXT,
    #         start_time TEXT NOT NULL,
    #         end_time TEXT NOT NULL,
    #         icon TEXT,
    #         priority TEXT DEFAULT 'medium',
    #         event_category TEXT DEFAULT 'general',
    #         created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    #         updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    #     )
    # """
    # )

    # # Lưu từng sự kiện
    # for event in events:
    #     cursor.execute(
    #         """
    #         INSERT INTO events (
    #             day_of_week,
    #             title, description, location, start_time, end_time,
    #              icon, priority, event_category
    #         )
    #         VALUES (%s,%s, %s, %s, %s, %s, %s, %s, %s)
    #         """,
    #         (
    #             event["DayOfWeek"],
    #             event["title"],
    #             event["description"],
    #             event["location"],
    #             event["start_time"],
    #             event["end_time"],
    #             event["icon"],
    #             event["priority"],
    #             event["event_category"],
    #         ),
    #     )

    # conn.commit()
    # cursor.close()
    print("✅ Lịch trình đã được lưu từ file thành công.")
    state["messages"].append(
        {"role": "assistant", "content": "✅ Lịch trình đã được lưu thành công."}
    )
    state["message_type"] = "schedule_created"

    return state
